apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: saensamecraftui
  name: saensamecraftui-pvc
  namespace: saensamecraftui
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi